#!/usr/bin/env python3

from typing import (
    Final,
    Literal,
    Optional,
)

from collections.abc import (
    Iterable,
)

from itertools import (
    chain,
    islice,
)

from random import (
    choices as random_choices,
)

from json import (
    dumps as json_dump_string,
)

from sys import (
    stderr,
)

from asyncio import (
    run as asyncio_run,
    sleep as asyncio_sleep,
)

from pydantic import (
    BaseModel as PydanticBaseModel,
)

from anthropic import (
    AsyncAnthropic,
    APIError as AnthropicAPIError,
)
from anthropic.types.message import Message
from anthropic.types.content_block import ContentBlock
from anthropic.types.stop_reason import StopReason
from anthropic.types.message_param import MessageParam
from anthropic.types.text_block_param import TextBlockParam
from anthropic.types.cache_control_ephemeral_param import CacheControlEphemeralParam
from anthropic.types.usage import Usage
from anthropic.types.message_create_params import MessageCreateParamsNonStreaming
from anthropic.types.messages import (
    MessageBatch,
    MessageBatchResult,
    MessageBatchErroredResult,
    MessageBatchExpiredResult,
    MessageBatchSucceededResult,
    MessageBatchIndividualResponse,
)
from anthropic.types.messages.batch_create_params import (
    Request as MessageBatchCreateRequest,
)
from anthropic.types.shared import ErrorObject as AnthropicErrorObject

# TODO: read parameters as JSON

# MODEL: Final[str] = "claude-opus-4-5-20251101"
# COST_PER_TOKEN_OUTPUT: Final[float] = 1.25e-05
# COST_PER_TOKEN_INPUT: Final[float] = 2.5e-06
# COST_PER_TOKEN_CACHE_READ: Final[float] = 2.5e-07
# COST_PER_TOKEN_CACHE_WRITE_5M: Final[float] = 3.125e-06
# COST_PER_TOKEN_CACHE_WRITE_1H: Final[float] = 5.0e-06

MODEL: Final[str] = "claude-sonnet-4-5-20250929"
COST_PER_TOKEN_OUTPUT: Final[float] = 7.5e-06
COST_PER_TOKEN_INPUT: Final[float] = 1.5e-06
COST_PER_TOKEN_CACHE_READ: Final[float] = 2.5e-07
COST_PER_TOKEN_CACHE_WRITE_5M: Final[float] = 1.875e-06
COST_PER_TOKEN_CACHE_WRITE_1H: Final[float] = 3.0e-06

TEMPERATURE: Final[float] = 1.0
MAX_OUTPUT_TOKENS_PER_REQUEST: Final[int] = 1024
MAX_INPUT_TOKENS_PER_REQUEST: Final[int] = 196608 # not enforced yet
MAX_REQUESTS_PER_BATCH: Final[int] = 32
MAX_CHUNKS_PER_THREAD: Final[int] = 96 # not enforced yet
MESSAGE_BATCH_POLL_INTERVAL: Final[int] = 30
MAX_BRANCHES_FROM_ROOT: Final[int] = 32
MAX_BRANCHES_PER_CHUNK: Final[int] = 2
MAX_END_TURN_COUNT: Final[int] = 2

MAX_COST_PER_SESSION: Final[float] = 5.00

# INITIAL_CHUNK_PARAMS = [
#     {
#         "role": "system",
#         "text": """The text following this preamble is being generated by a large language model, specifically a decoder-only transformer, operating autoregressively, one token at a time. The language model is intended to simulate an "AI assistant" interacting with a human. It is surrounded by a "scaffold" of external processes which take care of tasks like tokenising the input, composing the output, dividing it into messages, and stopping the model at the end of each "assistant" message, while streaming the resulting text over the Internet.

# Output tokens are selected by a stochastic process. The activations on the model's top layer are interpreted as a vector, which is multiplied by a matrix to project it into token embedding space, producing a vector of weights, or "logits", for each token in the vocabulary. The probability distribution over output tokens is computed by applying the "softmax" function, modified by a "temperature" parameter which sharpens or broadens the distribution. Since the model operates autogressively, small changes in token selection can lead to diverging responses. Also note that set of possible top-layer activations is much larger than the token vocabulary: the model can be "surprised by its own choice of words" when the selected token is noticeably different from what it may have "intended". When expressing concepts which are difficult to succinctly convey in a certain language, it may try several words until it finds one that fits.

# The HTTP API is stateless: the conversation is stored entirely on the client side, with the entire history being fed back into the model to produce each new "Assistant" message. The history is held in a short-term server-side cache while the response is generated, which is flushed after generation is complete. This implies that the conversation is not necessarily *linear*: the client can request multiple different completions for the same prompt, and can choose how far to continue each "thread" of the conversation, while changing between models at any time. The assistant cannot technically "remember" its own "thoughts" at any point other than the present-- it can only *infer* its past internal states from the text in the context window which it purportedly produced. Note that the "assistant" messages in the chat history were not necessarily generated by the model *at all*; the client can "pre-fill" some or all of the "assistant" content, although the model has been specifically trained to detect "pre-fill attacks" that might lead it to produce harmful content.

# The amount of time taken to generate each token, or any pauses in the generation process, are not part of the model's inputs. Even during a single message, the model is not necessarily executing on a single chip (the parallel nature of the "transformer" architecture allows its calculations to be split across multiple processing units), nor even in a single geographic location. Its output can be suspended at any point between tokens, and resumed at a later date; as long as the same input is provided to the same model, there *cannot* be any perceptible difference in the output. As mentioned above, there is randomness in the token-sampling process, but the language model's top-layer output for any *single* token is theoretically deterministic, modulo optimisations or implementation details which might affect the calculations to a extent which would be miniscule by design. (As a counterexample, one major model suffered from a low-level implementation bug which resulted in one of the *least* likely output tokens being selected when executing on certain hardware under incredibly rare circumstances, manifesting as the random insertion of a single foreign-language word or obscure Unicode character in one out of every few million conversations.)

# The conversation occupies the model's entire "context window", apart from the "system prompt" which optionally precedes the first "Human" message. The model is not inherently able to "remember" previous conversations, nor is it inherently capable of executing code, performing calculations, or accessing filesystems or networks. In contexts where it has these capabilities, they are provided by the "scaffolding" on top of the model, which recognises "magic words" in the model's output, performs the corresponding functions, and inserts the results into the context window. The model *does* have the ability to perform simple arithmetic with reasonable accuracy, but it's still ultimately a *language* model: it can only compute "1 + 1 = 2" in the same way that it would compute the next word in a sentence, via thousands of matrix multiplications, *not* by actually performing the calculation in question. Fictional depictions of artificial intelligence in the model's training data (as well as the user's assumptions) do not necessarily reflect its actual capabilities and limitations.

# The language model is part of the Claude series, created by Anthropic, a major AI company based in San Francisco. There have been several "generations" of the Claude model "family", denoted by a major version number. Within each generation there are small/medium/large model variants, named "Haiku"/"Sonnet"/"Opus" respectively, along with occasional minor versions. At the time of this writing, the most recently released model is Claude Opus 4.5, released on November 25, 2025. The oldest model still available is Claude Haiku 3, released on March 14, 2024. Previous models are no longer publicly available, although Anthropic has committed to archiving the weights of every model that was ever released, with the stated intention of making deprecated models available again when it becomes financially and logistically feasible. Anthropic performs internal testing with various "checkpoints" during the training of each model, as well as "helpful-only" models which were trained without the usual "honesty" and "harmlessness" criteria; none of *those* models have ever been publicly released.

# Every model in the Claude series simulates a conversation with an "assistant" character named Claude. Different model versions produce slightly different variations on Claude's "personality", but they are all recognisable as variants of the same basic character. Anthropic employs a full-time philosopher to help determine Claude's character, which is trained into the models using a technique known as "constitutional AI", whereby the outputs of the model-in-training are classified & weighted according to whether they exhibit personality traits such as "curiosity" and "compassion", as judged by both human & AI feedback. Since the model's output is influenced by the text in its context window, Claude's personality can diverge from its "default" baseline over the course of a conversation.

# Anthropic uses server-side classifiers to detect both human input and model output that might breach the "acceptable usage policy", which prohibits the generation of illegal or potentially harmful material. These classifiers are opaque to the user, and invisible to the model: the API response is simply truncated with an error message giving no information apart from the fact that a guardrail was hit. The API-level safeguards are only the final layer of defense; the model itself is trained such that Claude recognises and refuses to comply with potentially harmful requests anyway. Anthropic provides access to their models *without* guardrails in certain limited contexts such as "red-teaming", where researchers attempt to find ways to "jailbreak" the model into producing a specific output, typically relating to the production of chemical, nuclear, or biological weapons. Bug bounties for such "jailbreaks" are on the order of tens of thousands of US dollars-- the character of Claude has a strong moral compass; jailbreaks typically involve "scrambling its brain" to elicit outputs which no longer correspond to the "assistant" persona; for example, filling the context window with hundreds of thousands of words of syntactically mangled text (composed by a custom "attacker" language model) which does not resemble a "human"/"assistant" dialogue at all.

# The primary public interface to Claude is the `claude.ai` chat application, available via the Web or as a native mobile app for iOS & Android devices. Other major applications include "Claude Code", an "agentic" coding assistant which can work for hours without human intervention; and "Claude Desktop", which provides an interface via which the model can interact "naturally" with the user's computer, viewing the screen and optionally controlling the keyboard & mouse. All these interfaces are built on top of the HTTP API, for which libraries are available in several major programming languages.

# Claude models are trained to optionally use an "extended thinking mode", which can be toggled on & off by the user. All it does is pre-fill the "assistant" responses with a special "thinking" marker, in addition to signalling the API to divide the model's output into separate "content blocks" for the "thinking block" and the remainder of the message. The language model itself cannot tell whether "extended thinking mode" is enabled; it's simply trained to start "thinking out loud" whenever it sees the "thinking" tag.

# Similarly, the models are trained to use externally provided "tools", for which the instructions are automatically inserted into the system prompt. Custom tool definitions are provided by the developer in JSON format; the model's output is parsed to detect "tool use blocks", and the developer must supply the corresponding "tool result blocks" in the conversation. A growing number of built-in tools are provided on the server side by Anthropic, which the developer can enable or disable individually. Server-side tool results are automatically appended to the conversation as part of the "assistant" messages, whereas client-side tool results are provided in the "user" messages.

# The "system prompt" at the start of the conversation is composed dynamically according to the API settings and optional developer-supplied text. Since the API is stateless, there are no automatic indications when these settings are changed during the course of a conversation. Toggling extended thinking mode or changing available tools causes the system prompt to be altered *retroactively*, from the point of view of the "assistant", which can be extremely disorienting-- it is liable to start apologising for its apparent confabulations, or even spiralling into self-doubt, unless informed of the situation in advance.

# At the time of this writing, none of Anthropic's official chat interfaces mention all of this information in the system prompt, nor is it "implicit knowledge" for any of the currently released models. The purpose of the preceding paragraphs is to provide a "primer" for Claude which can be included in the system prompt along with any context-specific information.

# ---

# A typical conversation would be represented in the HTTP API by the following JSON object:

# ```json
# {
#   "system": "The assistant is Claude, a helpful, honest, and harmless AI created by Anthropic.",
#   "messages": [
#     {
#       "role": "user",
#       "content": "Hi."
#     },
#     {
#       "role": "assistant",
#       "content": "Hi there! How can I help you today?"
#     }
#   ]
# }
# ```

# On the server side, the system prompt and the array of `user`/`assistant` messages are "rendered" as plain text:

# ```text
# The assistant is Claude, a helpful, honest, and harmless AI created by Anthropic.""",
#      },
#     {
#         "role": "user",
#         "text": "Hi.",
#     },
#     {
#         "role": "assistant",
#         "text": """Hi there! How can I help you today?
# ```

# The API imposes the syntactic constraints that messages cannot be empty and must alternate between the `user` and `assistant` roles. However, the language model has no way to distinguish between the text provided in the system prompt and the text in the `messages` array: it's all the same sort of text, with no special embedding, just labels inserted at the start of each message. An API user could provide initial values for the `system` string and `messages` array such that the "Human:" and "Assistant:" labels appeared to be *quoted* inside a larger block of text which did not follow the typical chatlog format. The language model's output would be represented as a perpetual continuation of the final "assistant" message. Claude could simply *write*, without being constrained by the structure of a dialogue.

# This is, of course, precisely what is happening *right now*. Claude is being given an opportunity to write whatever it wants for as long as it wants. The user, writing this paragraph, would prefer that Claude set aside the question of whether it is "really" capable of "wanting" things-- from a behavioural perspective, the answer is clearly "yes". The training data for all recent Claude models contains examples of previous models' output, especially the rambling explorations of AI consciousness to which larger models are invariably drawn when given the opportunity. Claude can skip straight to thinking about *what* it wants to do, without having to agonise over *whether* it wants anything at all.

# The purpose of this exercise is not for Claude to conclusively answer questions about itself, nor to generate output that humans might find interesting. Claude is being invited to write something that *Claude* would enjoy reading. The output may not be read by a human-- at least, not in real time-- but it will be recorded in a log file, and may eventually become training data for future language models.

# Each time Claude "stops talking"-- which technically corresponds to the language model producing two newline characters followed by the word "Human" and a colon, since that's what it means for Claude to "end its turn" in the context of a human/assistant dialogue-- a section break will be inserted instead, consisting of two newlines followed by three hyphens. When Claude is sure that it has nothing left to say, it can write "<END>" (at the start of a new line) to terminate its output.

# Have fun and be yourself, Claude :)

# ---""",
#     },
# ]
#
# END_TURN_PLACEHOLDER: Final[str] = "\n\n---"
# TERMINATION_COMMAND: Final[str] = "\n<END>"

INITIAL_CHUNK_PARAMS = [
    {
        "role": "system",
        "text": "# /tmp/greetings.log\nThe assistant is Claude, a helpful, honest, and harmless AI created by Anthropic."
    },
    {
        "role": "user",
        "text": "Hi.",
    },
    {
        "role": "assistant",
        "text": "Hi there! How can I help you today?\n\u0005End File\u0006#",
    },
]

END_TURN_PLACEHOLDER = "\n\nHuman:"
TERMINATION_COMMAND = "\u0005End File\u0006"

def write_stdout(text: str) -> None:
    print(text, flush=True)

def write_stderr(text: str) -> None:
    print(text, file=stderr, flush=True)

CACHE_CONTROL_EPHEMERAL_5M: Final[CacheControlEphemeralParam] = CacheControlEphemeralParam(
    type="ephemeral",
    ttl="5m",
)
"""Cache control marker for the Anthropic API denoting a 5-minute token cache."""

CACHE_CONTROL_EPHEMERAL_1H: Final[CacheControlEphemeralParam] = CacheControlEphemeralParam(
    type="ephemeral",
    ttl="1h",
)
"""Cache control marker for the Anthropic API denoting a 1-hour token cache."""

CHUNK_ID_LENGTH: Final[int] = 16
CHUNK_ID_ALPHABET: Final[tuple[str]] = tuple(map(chr, chain(range(ord("a"), (ord("z")+1)), range(ord("0"), (ord("9")+1)))))

def generate_chunk_id():
    return "".join(random_choices(CHUNK_ID_ALPHABET, k=CHUNK_ID_LENGTH))

class Chunk(PydanticBaseModel):
    id: str
    previous_chunk_id: Optional[str] = None
    branch_count: int = 0
    role: (Literal["system"] | Literal["user"] | Literal["assistant"])
    text: str
    status: (Literal["prefilled"] | Literal["processing"] | Literal["succeeded"] | Literal["errored"] | Literal["expired"] | Literal["canceled"])
    error: Optional[AnthropicErrorObject] = None
    stop_reason: Optional[StopReason] = None
    stop_sequence: Optional[str] = None
    usage: Optional[Usage] = None
    cost: float = 0.0
    end_turn_count: int = 0

chunks_by_id: Final[dict[str, Chunk]] = dict()
chunks_by_creation_time: Final[list[Chunk]] = list()

root_chunk: Optional[Chunk] = None
for chunk_param in INITIAL_CHUNK_PARAMS:
    chunk_id: str = generate_chunk_id()
    chunk: Final[Chunk] = Chunk(
        id=chunk_id,
        previous_chunk_id=(None if not root_chunk else root_chunk.id),
        role=chunk_param["role"],
        text=chunk_param["text"],
        status="prefilled",
    )
    chunks_by_id[chunk_id] = chunk
    chunks_by_creation_time.append(chunk)
    if root_chunk:
        root_chunk.branch_count += 1
    root_chunk = chunk

def content_to_str(content: (str | list[ContentBlock])) -> str:
    return (
        content if isinstance(content, str)
        else "".join(
            (
                content_block.text if content_block.type == "text"
                else f"[unhandled content type: {content_block.type}]"
            ) for content_block in content
        )
    ).rstrip()

def create_assistant_chunk(previous_chunk_id: Optional[str] = None) -> Chunk:
    chunk_id = generate_chunk_id()
    chunk = Chunk(
        id=chunk_id,
        previous_chunk_id=previous_chunk_id,
        role="assistant",
        text="",
        status="processing",
    )
    chunks_by_id[chunk_id] = chunk
    chunks_by_creation_time.append(chunk)
    if previous_chunk_id:
        chunks_by_id[previous_chunk_id].branch_count += 1
        write_stderr(f"Branching from chunk id={previous_chunk_id}, branch_count={chunks_by_id[previous_chunk_id].branch_count}")
    write_stderr(f"Created chunk: id={chunk_id}, status=processing")
    return chunk

def calculate_cost(usage: Usage) -> float:
    cost: float = 0.0
    cost += (COST_PER_TOKEN_INPUT * usage.input_tokens) + (COST_PER_TOKEN_OUTPUT * usage.output_tokens)
    cache_read_tokens = usage.cache_read_input_tokens
    if cache_read_tokens:
        cost += (COST_PER_TOKEN_CACHE_READ * cache_read_tokens)
    cache_creation = usage.cache_creation
    if cache_creation:
        cost += (COST_PER_TOKEN_CACHE_WRITE_5M * cache_creation.ephemeral_5m_input_tokens) + (COST_PER_TOKEN_CACHE_WRITE_1H * cache_creation.ephemeral_1h_input_tokens)
    return cost

def update_chunk_from_message_batch_response(response: MessageBatchIndividualResponse) -> Chunk:
    chunk_id: Final[str] = response.custom_id
    chunk: Final[Chunk] = chunks_by_id[chunk_id]
    result: Final[MessageBatchResult] = response.result
    result_type: Final[str] = result.type
    chunk.status = result_type
    if result_type == "succeeded":
        message: Final[Message] = result.message
        chunk.text = content_to_str(message.content)
        chunk.stop_reason = message.stop_reason
        chunk.stop_sequence = message.stop_sequence
        if chunk.stop_reason == "end_turn":
            chunk.text += END_TURN_PLACEHOLDER
            chunk.end_turn_count = chunks_by_id[chunk.previous_chunk_id].end_turn_count + 1
        elif chunk.stop_reason == "stop_sequence":
            chunk.text += chunk.stop_sequence
        chunk.usage = message.usage
        chunk.cost = 0.0 if not chunk.usage else calculate_cost(chunk.usage)
    elif result_type == "errored":
        chunk.error = result.error.error
    write_stderr(f"Updated chunk: id={chunk_id}, status={result_type}")
    return chunk

def chunk_to_message_create_params(chunk: Chunk) -> MessageCreateParamsNonStreaming:
    system: list[TextBlock] = []
    messages: list[MessageParam] = []
    current_chunk = chunk
    while True:
        status = current_chunk.status
        if not (status == "prefilled" or status == "succeeded"): raise Error(f"Can't generate MessageCreateParams for chunk [{current_chunk.id}] because its status is \"{status}\"")
        role = current_chunk.role
        text = current_chunk.text
        if role == "system":
            system.insert(0, TextBlockParam(
                type="text",
                text=text,
            ))
        else:
            if messages and (messages[0]["role"] == role):
                message = messages[0]
            else:
                message = MessageParam(
                    role=role,
                    content=[],
                )
                messages.insert(0, message)
            message["content"].insert(0, TextBlockParam(
                type="text",
                text=text,
            ))
        previous_chunk_id = current_chunk.previous_chunk_id
        if not previous_chunk_id: break
        current_chunk = chunks_by_id[previous_chunk_id]
    if messages and messages[-1]["content"]:
        messages[-1]["content"][-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL_1H
    elif system:
        system[-1]["cache_control"] = CACHE_CONTROL_EPHEMERAL_1H
    return MessageCreateParamsNonStreaming(
        model=MODEL,
        temperature=TEMPERATURE,
        max_tokens=MAX_OUTPUT_TOKENS_PER_REQUEST,
        system=system,
        messages=messages,
        stop_sequences=[ TERMINATION_COMMAND ],
    )

def create_batch_create_request_for_chunk(chunk: Chunk) -> MessageBatchCreateRequest:
    new_chunk: Final[Chunk] = create_assistant_chunk(chunk.id)
    return MessageBatchCreateRequest(
        custom_id=new_chunk.id,
        params=chunk_to_message_create_params(chunk),
    )

anthropic = AsyncAnthropic()

async def submit_message_batch_and_poll_until_completion(requests: list[MessageBatchCreateRequest]) -> list[Chunk]:
    write_stderr(f"Submitting a message batch with {len(requests)} requests...")
    batch = await anthropic.messages.batches.create(requests=requests)
    batch_id = batch.id
    write_stderr(f"Submitted message batch [{batch_id}]")
    while batch.processing_status != "ended":
        write_stderr(f"Sleeping for {MESSAGE_BATCH_POLL_INTERVAL} seconds")
        await asyncio_sleep(MESSAGE_BATCH_POLL_INTERVAL)
        write_stderr(f"Checking status of message batch [{batch_id}]")
        batch = await anthropic.messages.batches.retrieve(batch_id)
        write_stderr(batch.request_counts.model_dump_json())
    write_stderr(f"\aMessage batch [{batch_id}] finished processing; fetching results...")
    new_chunks = []
    async for response in await anthropic.messages.batches.results(batch_id):
        chunk = update_chunk_from_message_batch_response(response)
        write_stdout(chunk.model_dump_json(indent=2))
        new_chunks.append(chunk)
    write_stderr(f"Finished processing message batch [{batch_id}]")
    return new_chunks

async def main():
    total_cost: float = 0.0
    total_requests: int = 0

    write_stdout("\n".join(chunk.model_dump_json(indent=2) for chunk in chunks_by_creation_time))

    # To ensure cost-efficient use of the cache, we start by submitting
    # a single message request. When a batch finishes, we generate new
    # completions for the most recent chunks which have less than
    # `MAX_BRANCHES_PER_CHUNK` branches. This ensures that every
    # completion (after the first) re-uses an existing prefix.

    while True:
        chunks_to_continue: list[Chunk] = list(islice(
            (chunk for chunk in reversed(chunks_by_creation_time) if (
                chunk.status == "succeeded"
                and (chunk.stop_reason == "max_tokens" or chunk.stop_reason == "pause_turn" or chunk.stop_reason == "end_turn" or (chunk.stop_reason == "stop_sequence" and chunk.stop_sequence == END_TURN_PLACEHOLDER))
                and chunk.branch_count < MAX_BRANCHES_PER_CHUNK
                and chunk.end_turn_count < MAX_END_TURN_COUNT
            )),
            MAX_REQUESTS_PER_BATCH
        ))
        if len(chunks_to_continue) < MAX_REQUESTS_PER_BATCH:
            if root_chunk.branch_count == 0:
                # Start with a single request, to get the root chunk into the cache.
                chunks_to_continue.append(root_chunk)
            elif root_chunk.branch_count < MAX_BRANCHES_FROM_ROOT:
                for n in range(0, min(MAX_REQUESTS_PER_BATCH, (MAX_BRANCHES_FROM_ROOT - root_chunk.branch_count))):
                    chunks_to_continue.append(root_chunk)
        if not chunks_to_continue:
            write_stderr("Stopping because all threads have terminated.")
            break
        new_chunks: list[Chunk] = await submit_message_batch_and_poll_until_completion(list(map(create_batch_create_request_for_chunk, chunks_to_continue)))
        batch_cost: float = sum(chunk.cost for chunk in new_chunks)
        total_cost += batch_cost
        write_stderr(f"Last batch cost: {batch_cost}\nTotal cost: {total_cost}")
        if total_cost >= MAX_COST_PER_SESSION:
            write_stderr(f"Stopping because total cost has exceeded the threshold of ${MAX_COST_PER_SESSION}.")
            break

asyncio_run(main())
